### ISSUE TITLE
Apps for Ljinux

### ISSUE THREAD

**Issue by singhamitoj** [bill88t/ljinux#23]
I have installed Ljinux on my RPI Pico, and I wanted to know if there were any programs/tools for it. If not, how do I create a program for it?

**Comment by bill88t** [comment]
At the moment this project is at it's infancy. We have yet to implement most of the coreutils, let alone apps. However, python scripting is not out of the question. The commands pexec and fpexec should help you with that. However, the based shell is still largely incomplete.

In order to create a ljinux "app" you only really need a .lja file (based shell script) in `/LjinuxRoot/bin`. That file will be made available as a command immediately. I have yet to write proper instructions on the api, so you will have to rely on reading the existing scripts of /bin and the work in progress manual.

**Comment by singhamitoj** [comment]
Okay, thanks for the info.
